import type { CursoDocenciaSlug } from "@/lib/docencia";

export type RegimeCurso = "diurno" | "pos-laboral";

export type CadeiraCurriculo = {
  id: string;
  codigo: string;
  nome: string;
  ano: number; // 1, 2, 3, 4
  semestre: number; // 1, 2
  regime: RegimeCurso;
  docente: string;
  docenteEmail?: string;
  docenteTelefone?: string;
  planoAnaliticoUrl?: string;
  descricao?: string;
  notaFinal?: number;
  resultado?: "Aprovado" | "Em Frequência" | "Reprovado" | "Excluído";
  anoConclusao?: string;
  teste1?: number;
  teste2?: number;
  trabalho?: number;
};

export type CurriculoCurso = {
  cursoSlug: CursoDocenciaSlug;
  cursoNome: string;
  cadeiras: CadeiraCurriculo[];
};

export const CURRICULOS_ESJ: Record<CursoDocenciaSlug, CurriculoCurso> = {
  jornalismo: {
    cursoSlug: "jornalismo",
    cursoNome: "Jornalismo",
    cadeiras: [
      // 1º ANO — 1º SEMESTRE
      {
        id: "jor-111",
        codigo: "JOR111",
        nome: "História de África Contemporânea",
        ano: 1,
        semestre: 1,
        regime: "diurno",
        docente: "Dr. Domingos Getimane",
        notaFinal: 12,
        resultado: "Aprovado",
        anoConclusao: "2019",
      },
      {
        id: "jor-112",
        codigo: "JOR112",
        nome: "História da Comunicação",
        ano: 1,
        semestre: 1,
        regime: "diurno",
        docente: "Dr. Alberto Mavila",
        notaFinal: 14,
        resultado: "Aprovado",
        anoConclusao: "2019",
      },
      {
        id: "jor-113",
        codigo: "JOR113",
        nome: "Língua Portuguesa I",
        ano: 1,
        semestre: 1,
        regime: "diurno",
        docente: "Dra. Maria Celeste",
        notaFinal: 12,
        resultado: "Aprovado",
        anoConclusao: "2018",
      },
      {
        id: "jor-114",
        codigo: "JOR114",
        nome: "Língua Inglesa I",
        ano: 1,
        semestre: 1,
        regime: "diurno",
        docente: "Prof. John Smith",
        notaFinal: 14,
        resultado: "Aprovado",
        anoConclusao: "2018",
      },
      {
        id: "jor-115",
        codigo: "JOR115",
        nome: "Introdução ao Jornalismo",
        ano: 1,
        semestre: 1,
        regime: "diurno",
        docente: "Prof. Tomás Macuácua",
        notaFinal: 14,
        resultado: "Aprovado",
        anoConclusao: "2020",
      },
      {
        id: "jor-116",
        codigo: "JOR116",
        nome: "Filosofia da Comunicação",
        ano: 1,
        semestre: 1,
        regime: "diurno",
        docente: "Dr. Salustiano Langa",
        notaFinal: 14,
        resultado: "Aprovado",
        anoConclusao: "2019",
      },
      {
        id: "jor-117",
        codigo: "JOR117",
        nome: "Método de Estudo",
        ano: 1,
        semestre: 1,
        regime: "diurno",
        docente: "Dra. Ana Maria Cossa",
        notaFinal: 14,
        resultado: "Aprovado",
        anoConclusao: "2019",
      },

      // 1º ANO — 2º SEMESTRE
      {
        id: "jor-121",
        codigo: "JOR121",
        nome: "Técnicas de Jornalismo",
        ano: 1,
        semestre: 2,
        regime: "diurno",
        docente: "Prof. Tomás Macuácua",
        notaFinal: 14,
        resultado: "Aprovado",
        anoConclusao: "2019",
      },
      {
        id: "jor-122",
        codigo: "JOR122",
        nome: "Introdução a Ciências Políticas",
        ano: 1,
        semestre: 2,
        regime: "diurno",
        docente: "Dr. Egídio Vaz",
        notaFinal: 12,
        resultado: "Aprovado",
        anoConclusao: "2019",
      },
      {
        id: "jor-123",
        codigo: "JOR123",
        nome: "Língua Portuguesa II",
        ano: 1,
        semestre: 2,
        regime: "diurno",
        docente: "Dra. Maria Celeste",
        notaFinal: 14,
        resultado: "Aprovado",
        anoConclusao: "2019",
      },
      {
        id: "jor-124",
        codigo: "JOR124",
        nome: "Língua Inglesa II",
        ano: 1,
        semestre: 2,
        regime: "diurno",
        docente: "Prof. John Smith",
        notaFinal: 14,
        resultado: "Aprovado",
        anoConclusao: "2019",
      },
      {
        id: "jor-125",
        codigo: "JOR125",
        nome: "Teoria da Comunicação",
        ano: 1,
        semestre: 2,
        regime: "diurno",
        docente: "Dr. Alberto Mavila",
        notaFinal: 14,
        resultado: "Aprovado",
        anoConclusao: "2019",
        planoAnaliticoUrl: "/documentos/plano-teoria-comunicacao-1.pdf",
      },
      {
        id: "jor-126",
        codigo: "JOR126",
        nome: "Introdução a Informática",
        ano: 1,
        semestre: 2,
        regime: "diurno",
        docente: "Eng. Mário Cuambe",
        notaFinal: 15,
        resultado: "Aprovado",
        anoConclusao: "2020",
      },
      {
        id: "jor-127",
        codigo: "JOR127",
        nome: "Antropologia Cultural",
        ano: 1,
        semestre: 2,
        regime: "diurno",
        docente: "Dr. Salustiano Langa",
        notaFinal: 15,
        resultado: "Aprovado",
        anoConclusao: "2019",
      },

      // 2º ANO — 1º SEMESTRE
      {
        id: "jor-211",
        codigo: "JOR211",
        nome: "Metodologia de Investigação Científica I",
        ano: 2,
        semestre: 1,
        regime: "diurno",
        docente: "Dr. Domingos Getimane",
        notaFinal: 15,
        resultado: "Aprovado",
        anoConclusao: "2018",
      },
      {
        id: "jor-212",
        codigo: "JOR212",
        nome: "Sociologia da Comunicação",
        ano: 2,
        semestre: 1,
        regime: "diurno",
        docente: "Dra. Isabel Cossa",
        notaFinal: 14,
        resultado: "Aprovado",
        anoConclusao: "2020",
      },
      {
        id: "jor-213",
        codigo: "JOR213",
        nome: "Técnicas de Jornalismo II",
        ano: 2,
        semestre: 1,
        regime: "diurno",
        docente: "Prof. Tomás Macuácua",
        notaFinal: 16,
        resultado: "Aprovado",
        anoConclusao: "2020",
      },
      {
        id: "jor-214",
        codigo: "JOR214",
        nome: "Noções de Estatística",
        ano: 2,
        semestre: 1,
        regime: "diurno",
        docente: "Dr. Carlos Nhantumbo",
        notaFinal: 14,
        resultado: "Aprovado",
        anoConclusao: "2023",
      },
      {
        id: "jor-215",
        codigo: "JOR215",
        nome: "Fotojornalismo",
        ano: 2,
        semestre: 1,
        regime: "diurno",
        docente: "Prof. Inácio Mabote",
        notaFinal: 11,
        resultado: "Aprovado",
        anoConclusao: "2020",
      },
      {
        id: "jor-216",
        codigo: "JOR216",
        nome: "Técnicas de Comunicação e Expressão",
        ano: 2,
        semestre: 1,
        regime: "diurno",
        docente: "Dra. Maria Celeste",
        notaFinal: 16,
        resultado: "Aprovado",
        anoConclusao: "2020",
      },
      {
        id: "jor-217",
        codigo: "JOR217",
        nome: "Teorias de Jornalismo",
        ano: 2,
        semestre: 1,
        regime: "diurno",
        docente: "Dr. Alberto Mavila",
        notaFinal: 13,
        resultado: "Aprovado",
        anoConclusao: "2020",
      },

      // 2º ANO — 2º SEMESTRE
      {
        id: "jor-221",
        codigo: "JOR221",
        nome: "Metodologia de Investigação Científica II",
        ano: 2,
        semestre: 2,
        regime: "diurno",
        docente: "Dr. Domingos Getimane",
        notaFinal: 16,
        resultado: "Aprovado",
        anoConclusao: "2020",
      },
      {
        id: "jor-222",
        codigo: "JOR222",
        nome: "Semiótica da Comunicação",
        ano: 2,
        semestre: 2,
        regime: "diurno",
        docente: "Dr. Alberto Mavila",
        notaFinal: 16,
        resultado: "Aprovado",
        anoConclusao: "2020",
      },
      {
        id: "jor-223",
        codigo: "JOR223",
        nome: "Jornalismo Investigativo",
        ano: 2,
        semestre: 2,
        regime: "diurno",
        docente: "Dra. Isabel Cossa",
        notaFinal: 15,
        resultado: "Aprovado",
        anoConclusao: "2020",
      },
      {
        id: "jor-224",
        codigo: "JOR224",
        nome: "Técnicas de Produção Gráfica",
        ano: 2,
        semestre: 2,
        regime: "diurno",
        docente: "Prof. Armindo Nhantumbo",
        notaFinal: 14,
        resultado: "Aprovado",
        anoConclusao: "2020",
      },
      {
        id: "jor-225",
        codigo: "JOR225",
        nome: "Fundamentos de Economia",
        ano: 2,
        semestre: 2,
        regime: "diurno",
        docente: "Dr. Carlos Nhantumbo",
        notaFinal: 13,
        resultado: "Aprovado",
        anoConclusao: "2020",
      },
      {
        id: "jor-226",
        codigo: "JOR226",
        nome: "Noções de Direito",
        ano: 2,
        semestre: 2,
        regime: "diurno",
        docente: "Dr. Egídio Vaz",
        notaFinal: 12,
        resultado: "Aprovado",
        anoConclusao: "2020",
      },
      {
        id: "jor-227",
        codigo: "JOR227",
        nome: "Psicologia Geral e da Comunicação",
        ano: 2,
        semestre: 2,
        regime: "diurno",
        docente: "Dra. Vanessa Sitoe",
        notaFinal: 15,
        resultado: "Aprovado",
        anoConclusao: "2018",
      },

      // 3º ANO — 1º SEMESTRE
      {
        id: "jor-311",
        codigo: "JOR311",
        nome: "Laboratório de Jornalismo Impresso I",
        ano: 3,
        semestre: 1,
        regime: "diurno",
        docente: "Prof. Tomás Macuácua",
        notaFinal: 12,
        resultado: "Aprovado",
        anoConclusao: "2021",
      },
      {
        id: "jor-312",
        codigo: "JOR312",
        nome: "Laboratório de Telejornalismo I",
        ano: 3,
        semestre: 1,
        regime: "diurno",
        docente: "Dra. Marta Langa",
        notaFinal: 11,
        resultado: "Aprovado",
        anoConclusao: "2021",
      },
      {
        id: "jor-313",
        codigo: "JOR313",
        nome: "Laboratório de Radiojornalismo I",
        ano: 3,
        semestre: 1,
        regime: "diurno",
        docente: "Prof. Inácio Mabote",
        notaFinal: 15,
        resultado: "Aprovado",
        anoConclusao: "2021",
      },
      {
        id: "jor-314",
        codigo: "JOR314",
        nome: "Leitura e Crítica dos Meios de Comunicação",
        ano: 3,
        semestre: 1,
        regime: "diurno",
        docente: "Dr. Salomão Moyana",
        notaFinal: 14,
        resultado: "Aprovado",
        anoConclusao: "2021",
      },
      {
        id: "jor-315",
        codigo: "JOR315",
        nome: "Assessoria de Imprensa",
        ano: 3,
        semestre: 1,
        regime: "diurno",
        docente: "Dra. Helena Tembe",
        notaFinal: 11,
        resultado: "Aprovado",
        anoConclusao: "2021",
      },

      // 3º ANO — 2º SEMESTRE
      {
        id: "jor-321",
        codigo: "JOR321",
        nome: "Laboratório de Jornalismo Impresso II",
        ano: 3,
        semestre: 2,
        regime: "diurno",
        docente: "Prof. Tomás Macuácua",
        notaFinal: 13,
        resultado: "Aprovado",
        anoConclusao: "2021",
      },
      {
        id: "jor-322",
        codigo: "JOR322",
        nome: "Laboratório de Telejornalismo II",
        ano: 3,
        semestre: 2,
        regime: "diurno",
        docente: "Dra. Marta Langa",
        notaFinal: 13,
        resultado: "Aprovado",
        anoConclusao: "2021",
      },
      {
        id: "jor-323",
        codigo: "JOR323",
        nome: "Laboratório de Rádio jornalismo II",
        ano: 3,
        semestre: 2,
        regime: "diurno",
        docente: "Prof. Inácio Mabote",
        notaFinal: 14,
        resultado: "Aprovado",
        anoConclusao: "2021",
      },
      {
        id: "jor-324",
        codigo: "JOR324",
        nome: "Comunicação para Desenvolvimento",
        ano: 3,
        semestre: 2,
        regime: "diurno",
        docente: "Dr. Alberto Mavila",
        notaFinal: 14,
        resultado: "Aprovado",
        anoConclusao: "2021",
      },
      {
        id: "jor-325",
        codigo: "JOR325",
        nome: "Direitos Humanos e Cidadania",
        ano: 3,
        semestre: 2,
        regime: "diurno",
        docente: "Dr. Egídio Vaz",
        notaFinal: 16,
        resultado: "Aprovado",
        anoConclusao: "2022",
      },
      {
        id: "jor-326",
        codigo: "JOR326",
        nome: "Comunicação Política",
        ano: 3,
        semestre: 2,
        regime: "diurno",
        docente: "Dr. Salomão Moyana",
        notaFinal: 16,
        resultado: "Aprovado",
        anoConclusao: "2021",
      },

      // 4º ANO — 1º SEMESTRE
      {
        id: "jor-411",
        codigo: "JOR411",
        nome: "Web Jornalismo",
        ano: 4,
        semestre: 1,
        regime: "diurno",
        docente: "Eng. Mário Cuambe",
        notaFinal: 12,
        resultado: "Aprovado",
        anoConclusao: "2022",
      },
      {
        id: "jor-412",
        codigo: "JOR412",
        nome: "Projecto de Investigação Jornalística",
        ano: 4,
        semestre: 1,
        regime: "diurno",
        docente: "Dr. Domingos Getimane",
        notaFinal: 12,
        resultado: "Aprovado",
        anoConclusao: "2022",
      },
      {
        id: "jor-413",
        codigo: "JOR413",
        nome: "Jornalismo Especializado",
        ano: 4,
        semestre: 1,
        regime: "diurno",
        docente: "Dra. Isabel Cossa",
        notaFinal: 12,
        resultado: "Aprovado",
        anoConclusao: "2022",
      },
      {
        id: "jor-414",
        codigo: "JOR414",
        nome: "Legislação e Ética da Comunicação",
        ano: 4,
        semestre: 1,
        regime: "diurno",
        docente: "Dr. Salomão Moyana",
        notaFinal: 14,
        resultado: "Aprovado",
        anoConclusao: "2022",
      },
      {
        id: "jor-415",
        codigo: "JOR415",
        nome: "Direitos Humanos e Cidadania",
        ano: 4,
        semestre: 1,
        regime: "diurno",
        docente: "Dr. Egídio Vaz",
        notaFinal: 16,
        resultado: "Aprovado",
        anoConclusao: "2022",
      },
    ],
  },
  "publicidade-e-marketing": {
    cursoSlug: "publicidade-e-marketing",
    cursoNome: "Publicidade e Marketing",
    cadeiras: [
      {
        id: "pm-101",
        codigo: "PM101",
        nome: "Introdução ao Marketing",
        ano: 1,
        semestre: 1,
        regime: "diurno",
        docente: "Dr. Carlos Nhantumbo",
        docenteEmail: "carlos.nhantumbo@esj.ac.mz",
        planoAnaliticoUrl: "/documentos/plano-introducao-marketing.pdf",
        descricao: "Conceitos fundamentais de mercado, comportamento do consumidor e marketing mix.",
        notaFinal: 15,
        resultado: "Aprovado",
        anoConclusao: "2021",
      },
      {
        id: "pm-102",
        codigo: "PM102",
        nome: "Criação e Redação Publicitária",
        ano: 1,
        semestre: 2,
        regime: "diurno",
        docente: "Dra. Vanessa Sitoe",
        docenteEmail: "vanessa.sitoe@esj.ac.mz",
        planoAnaliticoUrl: "/documentos/plano-redacao-publicitaria.pdf",
        descricao: "Desenvolvimento de conceitos criativos, copy para anúncios e campanhas de media.",
        notaFinal: 14,
        resultado: "Aprovado",
        anoConclusao: "2021",
      },
    ],
  },
  "relacoes-publicas": {
    cursoSlug: "relacoes-publicas",
    cursoNome: "Relações Públicas",
    cadeiras: [
      {
        id: "rp-101",
        codigo: "RP101",
        nome: "Comunicação Organizacional",
        ano: 1,
        semestre: 1,
        regime: "diurno",
        docente: "Dra. Helena Tembe",
        docenteEmail: "helena.tembe@esj.ac.mz",
        planoAnaliticoUrl: "/documentos/plano-comunicacao-organizacional.pdf",
        descricao: "Estratégias de comunicação interna, gestão de imagem institucional e assessoria de imprensa.",
        notaFinal: 16,
        resultado: "Aprovado",
        anoConclusao: "2021",
      },
      {
        id: "rp-102",
        codigo: "RP102",
        nome: "Gestão de Crise e Imagem",
        ano: 2,
        semestre: 1,
        regime: "diurno",
        docente: "Dr. Fernando Mucavele",
        docenteEmail: "fernando.mucavele@esj.ac.mz",
        planoAnaliticoUrl: "/documentos/plano-gestao-crise.pdf",
        descricao: "Protocolos de prevenção, gestão de reputação e comunicação em momentos críticos.",
        notaFinal: 15,
        resultado: "Aprovado",
        anoConclusao: "2022",
      },
    ],
  },
  "biblioteconomia-e-documentacao": {
    cursoSlug: "biblioteconomia-e-documentacao",
    cursoNome: "Biblioteconomia e Documentação",
    cadeiras: [
      {
        id: "bd-101",
        codigo: "BD101",
        nome: "Gestão de Sistemas de Informação",
        ano: 1,
        semestre: 1,
        regime: "diurno",
        docente: "Dr. Jorge Mabote",
        docenteEmail: "jorge.mabote@esj.ac.mz",
        planoAnaliticoUrl: "/documentos/plano-gestao-sistemas-informacao.pdf",
        descricao: "Classificação bibliográfica, catalogação digital e preservação de acervos documentais.",
        notaFinal: 14,
        resultado: "Aprovado",
        anoConclusao: "2021",
      },
    ],
  },
};

export function getCurriculoPorCurso(
  cursoSlug: CursoDocenciaSlug,
  regime?: RegimeCurso
): CadeiraCurriculo[] {
  const c = CURRICULOS_ESJ[cursoSlug];
  if (!c) return [];
  if (!regime) return c.cadeiras;
  const filtradas = c.cadeiras.filter((cad) => cad.regime === regime);
  return filtradas.length > 0 ? filtradas : c.cadeiras;
}
