// Dias internacionais/mundiais assinalados pela ONU e outros organismos internacionais,
// independentes do calendário da ESJ. Indexados por "MM-DD" (repetem-se todos os anos).

export type DataInternacional = { mesDia: string; titulo: string };

export const DATAS_INTERNACIONAIS: DataInternacional[] = [
  { mesDia: "01-04", titulo: "Dia Mundial do Braille" },
  { mesDia: "01-24", titulo: "Dia Internacional da Educação" },
  { mesDia: "01-27", titulo: "Dia Internacional em Memória das Vítimas do Holocausto" },
  { mesDia: "02-04", titulo: "Dia Mundial do Cancro" },
  { mesDia: "02-11", titulo: "Dia Internacional das Mulheres e Raparigas na Ciência" },
  { mesDia: "02-13", titulo: "Dia Mundial do Rádio" },
  { mesDia: "02-20", titulo: "Dia Mundial da Justiça Social" },
  { mesDia: "02-21", titulo: "Dia Internacional da Língua Materna" },
  { mesDia: "03-08", titulo: "Dia Internacional da Mulher" },
  { mesDia: "03-20", titulo: "Dia Internacional da Felicidade" },
  { mesDia: "03-21", titulo: "Dia Internacional para a Eliminação da Discriminação Racial" },
  { mesDia: "03-21", titulo: "Dia Mundial da Poesia" },
  { mesDia: "03-22", titulo: "Dia Mundial da Água" },
  { mesDia: "03-23", titulo: "Dia Meteorológico Mundial" },
  { mesDia: "04-02", titulo: "Dia Mundial de Consciencialização do Autismo" },
  { mesDia: "04-07", titulo: "Dia Mundial da Saúde" },
  { mesDia: "04-23", titulo: "Dia Mundial do Livro e do Direito de Autor" },
  { mesDia: "04-29", titulo: "Dia Internacional da Dança" },
  { mesDia: "05-03", titulo: "Dia Mundial da Liberdade de Imprensa" },
  { mesDia: "05-15", titulo: "Dia Internacional das Famílias" },
  { mesDia: "05-17", titulo: "Dia Mundial das Telecomunicações e da Sociedade da Informação" },
  { mesDia: "05-21", titulo: "Dia Mundial da Diversidade Cultural para o Diálogo e o Desenvolvimento" },
  { mesDia: "05-31", titulo: "Dia Mundial Sem Tabaco" },
  { mesDia: "06-05", titulo: "Dia Mundial do Ambiente" },
  { mesDia: "06-08", titulo: "Dia Mundial dos Oceanos" },
  { mesDia: "06-12", titulo: "Dia Mundial contra o Trabalho Infantil" },
  { mesDia: "06-20", titulo: "Dia Mundial do Refugiado" },
  { mesDia: "06-21", titulo: "Dia Internacional da Música" },
  { mesDia: "06-21", titulo: "Dia Internacional do Yoga" },
  { mesDia: "07-11", titulo: "Dia Mundial da População" },
  { mesDia: "07-18", titulo: "Dia Internacional de Nelson Mandela" },
  { mesDia: "07-30", titulo: "Dia Mundial contra o Tráfico de Pessoas" },
  { mesDia: "08-09", titulo: "Dia Internacional dos Povos Indígenas" },
  { mesDia: "08-12", titulo: "Dia Internacional da Juventude" },
  { mesDia: "08-19", titulo: "Dia Mundial Humanitário" },
  { mesDia: "08-23", titulo: "Dia Internacional de Lembrança do Tráfico de Escravos e da sua Abolição" },
  { mesDia: "09-08", titulo: "Dia Internacional da Alfabetização" },
  { mesDia: "09-15", titulo: "Dia Internacional da Democracia" },
  { mesDia: "09-21", titulo: "Dia Internacional da Paz" },
  { mesDia: "09-27", titulo: "Dia Mundial do Turismo" },
  { mesDia: "09-28", titulo: "Dia Mundial do Acesso Universal à Informação" },
  { mesDia: "09-29", titulo: "Dia Internacional de Consciencialização sobre a Perda e Desperdício de Alimentos" },
  { mesDia: "10-01", titulo: "Dia Internacional das Pessoas Idosas" },
  { mesDia: "10-05", titulo: "Dia Mundial dos Professores" },
  { mesDia: "10-10", titulo: "Dia Mundial da Saúde Mental" },
  { mesDia: "10-16", titulo: "Dia Mundial da Alimentação" },
  { mesDia: "10-17", titulo: "Dia Internacional para a Erradicação da Pobreza" },
  { mesDia: "10-24", titulo: "Dia das Nações Unidas" },
  { mesDia: "11-16", titulo: "Dia Internacional da Tolerância" },
  { mesDia: "11-20", titulo: "Dia Universal da Criança" },
  { mesDia: "11-21", titulo: "Dia Mundial da Televisão" },
  { mesDia: "11-25", titulo: "Dia Internacional para a Eliminação da Violência contra as Mulheres" },
  { mesDia: "12-01", titulo: "Dia Mundial de Luta contra a Sida" },
  { mesDia: "12-03", titulo: "Dia Internacional das Pessoas com Deficiência" },
  { mesDia: "12-10", titulo: "Dia dos Direitos Humanos" },
];

export function datasInternacionaisEm(mesDia: string): DataInternacional[] {
  return DATAS_INTERNACIONAIS.filter((d) => d.mesDia === mesDia);
}
