// Dias internacionais/mundiais assinalados pela ONU e por outros organismos internacionais
// (OMS, UNESCO, OMPI, OIT, UPU, União Africana, etc.), independentes do calendário da ESJ.
// Indexados por "MM-DD" (repetem-se todos os anos). Lista não exaustiva — inclui apenas datas
// verificadas; datas sem observância internacional amplamente reconhecida ficam de fora.

export type DataInternacional = { mesDia: string; titulo: string };

export const DATAS_INTERNACIONAIS: DataInternacional[] = [
  { mesDia: "01-01", titulo: "Ano Novo (observância internacional)" },
  { mesDia: "01-04", titulo: "Dia Mundial do Braille" },
  { mesDia: "01-24", titulo: "Dia Internacional da Educação" },
  { mesDia: "01-27", titulo: "Dia Internacional em Memória das Vítimas do Holocausto" },
  { mesDia: "02-03", titulo: "Dia Internacional da Fraternidade Humana (assinalado a 4 de Fevereiro)" },
  { mesDia: "02-04", titulo: "Dia Mundial do Cancro" },
  { mesDia: "02-04", titulo: "Dia Internacional da Fraternidade Humana" },
  { mesDia: "02-06", titulo: "Dia Internacional de Tolerância Zero à Mutilação Genital Feminina" },
  { mesDia: "02-11", titulo: "Dia Internacional das Mulheres e Raparigas na Ciência" },
  { mesDia: "02-13", titulo: "Dia Mundial do Rádio" },
  { mesDia: "02-20", titulo: "Dia Mundial da Justiça Social" },
  { mesDia: "02-21", titulo: "Dia Internacional da Língua Materna" },
  { mesDia: "03-01", titulo: "Dia da Zero Discriminação" },
  { mesDia: "03-03", titulo: "Dia Mundial da Vida Selvagem" },
  { mesDia: "03-08", titulo: "Dia Internacional da Mulher" },
  { mesDia: "03-15", titulo: "Dia Mundial dos Direitos do Consumidor" },
  { mesDia: "03-20", titulo: "Dia Internacional da Felicidade" },
  { mesDia: "03-21", titulo: "Dia Internacional para a Eliminação da Discriminação Racial" },
  { mesDia: "03-21", titulo: "Dia Mundial da Poesia" },
  { mesDia: "03-22", titulo: "Dia Mundial da Água" },
  { mesDia: "03-23", titulo: "Dia Meteorológico Mundial" },
  { mesDia: "03-24", titulo: "Dia Mundial da Tuberculose" },
  { mesDia: "04-02", titulo: "Dia Mundial de Consciencialização do Autismo" },
  { mesDia: "04-07", titulo: "Dia Mundial da Saúde" },
  { mesDia: "04-22", titulo: "Dia Internacional da Mãe Terra" },
  { mesDia: "04-23", titulo: "Dia Mundial do Livro e do Direito de Autor" },
  { mesDia: "04-25", titulo: "Dia Mundial da Malária" },
  { mesDia: "04-26", titulo: "Dia Mundial da Propriedade Intelectual" },
  { mesDia: "04-28", titulo: "Dia Mundial da Segurança e Saúde no Trabalho" },
  { mesDia: "04-29", titulo: "Dia Internacional da Dança" },
  { mesDia: "05-01", titulo: "Dia Internacional do Trabalhador" },
  { mesDia: "05-03", titulo: "Dia Mundial da Liberdade de Imprensa" },
  { mesDia: "05-15", titulo: "Dia Internacional das Famílias" },
  { mesDia: "05-17", titulo: "Dia Mundial das Telecomunicações e da Sociedade da Informação" },
  { mesDia: "05-21", titulo: "Dia Mundial da Diversidade Cultural para o Diálogo e o Desenvolvimento" },
  { mesDia: "05-22", titulo: "Dia Internacional da Diversidade Biológica" },
  { mesDia: "05-25", titulo: "Dia de África" },
  { mesDia: "05-29", titulo: "Dia Internacional das Forças de Manutenção da Paz da ONU" },
  { mesDia: "05-31", titulo: "Dia Mundial Sem Tabaco" },
  { mesDia: "06-04", titulo: "Dia Internacional das Crianças Vítimas Inocentes de Agressão" },
  { mesDia: "06-05", titulo: "Dia Mundial do Ambiente" },
  { mesDia: "06-08", titulo: "Dia Mundial dos Oceanos" },
  { mesDia: "06-12", titulo: "Dia Mundial contra o Trabalho Infantil" },
  { mesDia: "06-16", titulo: "Dia da Criança Africana" },
  { mesDia: "06-20", titulo: "Dia Mundial do Refugiado" },
  { mesDia: "06-21", titulo: "Dia Internacional da Música" },
  { mesDia: "06-21", titulo: "Dia Internacional do Yoga" },
  { mesDia: "06-23", titulo: "Dia das Nações Unidas para o Serviço Público" },
  { mesDia: "06-25", titulo: "Dia Internacional da Independência dos Povos (alusivo às independências africanas)" },
  { mesDia: "06-26", titulo: "Dia Internacional de Apoio às Vítimas de Tortura" },
  { mesDia: "06-26", titulo: "Dia Internacional de Luta contra o Uso Indevido e o Tráfico Ilícito de Drogas" },
  { mesDia: "07-11", titulo: "Dia Mundial da População" },
  { mesDia: "07-15", titulo: "Dia Mundial das Competências dos Jovens" },
  { mesDia: "07-18", titulo: "Dia Internacional de Nelson Mandela" },
  { mesDia: "07-30", titulo: "Dia Mundial contra o Tráfico de Pessoas" },
  { mesDia: "07-30", titulo: "Dia Internacional da Amizade" },
  { mesDia: "08-09", titulo: "Dia Internacional dos Povos Indígenas" },
  { mesDia: "08-12", titulo: "Dia Internacional da Juventude" },
  { mesDia: "08-19", titulo: "Dia Mundial Humanitário" },
  { mesDia: "08-23", titulo: "Dia Internacional de Lembrança do Tráfico de Escravos e da sua Abolição" },
  { mesDia: "08-29", titulo: "Dia Internacional contra os Testes Nucleares" },
  { mesDia: "09-07", titulo: "Dia Internacional da Alfabetização (assinalado a 8 de Setembro)" },
  { mesDia: "09-08", titulo: "Dia Internacional da Alfabetização" },
  { mesDia: "09-12", titulo: "Dia das Nações Unidas para a Cooperação Sul-Sul" },
  { mesDia: "09-15", titulo: "Dia Internacional da Democracia" },
  { mesDia: "09-16", titulo: "Dia Internacional para a Preservação da Camada de Ozono" },
  { mesDia: "09-21", titulo: "Dia Internacional da Paz" },
  { mesDia: "09-25", titulo: "Dia Internacional da Paz (assinalado a 21 de Setembro)" },
  { mesDia: "09-27", titulo: "Dia Mundial do Turismo" },
  { mesDia: "09-28", titulo: "Dia Mundial do Acesso Universal à Informação" },
  { mesDia: "09-29", titulo: "Dia Internacional de Consciencialização sobre a Perda e Desperdício de Alimentos" },
  { mesDia: "10-01", titulo: "Dia Internacional das Pessoas Idosas" },
  { mesDia: "10-04", titulo: "Dia Mundial do Animal" },
  { mesDia: "10-05", titulo: "Dia Mundial dos Professores" },
  { mesDia: "10-09", titulo: "Dia Mundial dos Correios" },
  { mesDia: "10-10", titulo: "Dia Mundial da Saúde Mental" },
  { mesDia: "10-11", titulo: "Dia Internacional da Rapariga" },
  { mesDia: "10-16", titulo: "Dia Mundial da Alimentação" },
  { mesDia: "10-17", titulo: "Dia Internacional para a Erradicação da Pobreza" },
  { mesDia: "10-24", titulo: "Dia das Nações Unidas" },
  { mesDia: "11-06", titulo: "Dia Internacional para a Prevenção da Exploração do Ambiente na Guerra e nos Conflitos Armados" },
  { mesDia: "11-14", titulo: "Dia Mundial da Diabetes" },
  { mesDia: "11-16", titulo: "Dia Internacional da Tolerância" },
  { mesDia: "11-19", titulo: "Dia Mundial da Casa de Banho" },
  { mesDia: "11-20", titulo: "Dia Universal da Criança" },
  { mesDia: "11-21", titulo: "Dia Mundial da Televisão" },
  { mesDia: "11-25", titulo: "Dia Internacional para a Eliminação da Violência contra as Mulheres" },
  { mesDia: "12-01", titulo: "Dia Mundial de Luta contra a Sida" },
  { mesDia: "12-03", titulo: "Dia Internacional das Pessoas com Deficiência" },
  { mesDia: "12-05", titulo: "Dia Internacional dos Voluntários" },
  { mesDia: "12-09", titulo: "Dia Internacional de Combate à Corrupção" },
  { mesDia: "12-10", titulo: "Dia dos Direitos Humanos" },
  { mesDia: "12-18", titulo: "Dia Internacional dos Migrantes" },
  { mesDia: "12-20", titulo: "Dia Internacional da Solidariedade Humana" },
];

export function datasInternacionaisEm(mesDia: string): DataInternacional[] {
  return DATAS_INTERNACIONAIS.filter((d) => d.mesDia === mesDia);
}

/** Extrai MM-DD de uma chave ISO AAAA-MM-DD. */
export function mesDiaDeIso(iso: string): string {
  const m = iso.match(/^\d{4}-(\d{2}-\d{2})/);
  return m ? m[1] : iso.slice(5, 10);
}
