import { getSupabase } from "@/lib/supabase";
import {
  ANO_LECTIVO,
  classificacao,
  mediaFinal,
  type Nivel,
  type Regime,
} from "@/lib/admissao";

export type LinhaPauta = {
  id: string;
  anoLectivo: string;
  nivel: Nivel;
  curso: string;
  regime: Regime;
  apelido: string;
  nome: string;
  notaPortugues: number;
  notaHistoria: number;
  media: number;
  resultado: "Admitido" | "Não admitido";
  publicado: boolean;
};

export type PautaPublica = {
  anoLectivo: string;
  nivel: Nivel;
  curso: string;
  regime: Regime;
  linhas: LinhaPauta[];
};

type PautaRow = {
  id: string;
  ano_lectivo: string;
  nivel: string;
  curso: string;
  regime: string;
  apelido: string;
  nome: string;
  nota_portugues: number | string;
  nota_historia: number | string;
  publicado: boolean;
};

function num(value: number | string) {
  return typeof value === "number" ? value : Number(value);
}

export function mapLinha(row: PautaRow): LinhaPauta {
  const notaPortugues = num(row.nota_portugues);
  const notaHistoria = num(row.nota_historia);
  const media = mediaFinal(notaPortugues, notaHistoria);
  return {
    id: row.id,
    anoLectivo: row.ano_lectivo,
    nivel: row.nivel as Nivel,
    curso: row.curso,
    regime: row.regime as Regime,
    apelido: row.apelido,
    nome: row.nome,
    notaPortugues,
    notaHistoria,
    media,
    resultado: classificacao(media),
    publicado: row.publicado,
  };
}

export function ordenarPauta(linhas: LinhaPauta[]) {
  return [...linhas].sort((a, b) => {
    const apelido = a.apelido.localeCompare(b.apelido, "pt", { sensitivity: "base" });
    if (apelido !== 0) return apelido;
    return a.nome.localeCompare(b.nome, "pt", { sensitivity: "base" });
  });
}

export function letraGrupo(apelido: string) {
  const letter = apelido
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .charAt(0)
    .toUpperCase();
  return /[A-Z]/.test(letter) ? letter : "#";
}

export function rankingMerito(linhas: LinhaPauta[]) {
  const byMedia = [...linhas].sort((a, b) => {
    if (b.media !== a.media) return b.media - a.media;
    const apelido = a.apelido.localeCompare(b.apelido, "pt", { sensitivity: "base" });
    if (apelido !== 0) return apelido;
    return a.nome.localeCompare(b.nome, "pt", { sensitivity: "base" });
  });
  const rank = new Map<string, number>();
  byMedia.forEach((linha, i) => rank.set(linha.id, i + 1));
  return rank;
}

const DEMO_JORNALISMO_DIURNO: Omit<PautaRow, "id" | "publicado">[] = [
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Alfredo",
    nome: "Ana Maria",
    nota_portugues: 9.5,
    nota_historia: 7.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Banze",
    nome: "Carlos Eduardo",
    nota_portugues: 14.0,
    nota_historia: 6.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Bila",
    nome: "Esperança",
    nota_portugues: 12.5,
    nota_historia: 10.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Buque",
    nome: "João Pedro",
    nota_portugues: 6.0,
    nota_historia: 12.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Chauque",
    nome: "Lurdes",
    nota_portugues: 5.5,
    nota_historia: 11.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Chirindza",
    nome: "Pedro António",
    nota_portugues: 6.0,
    nota_historia: 6.5,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Chissano",
    nome: "Fátima",
    nota_portugues: 11.0,
    nota_historia: 16.5,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Come",
    nome: "Miguel",
    nota_portugues: 6.5,
    nota_historia: 8.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Cossa",
    nome: "Helena",
    nota_portugues: 14.0,
    nota_historia: 18.5,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Cuamba",
    nome: "Daniel",
    nota_portugues: 13.0,
    nota_historia: 10.5,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Cuinica",
    nome: "Inês",
    nota_portugues: 18.5,
    nota_historia: 5.5,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Cumbe",
    nome: "Rui",
    nota_portugues: 17.0,
    nota_historia: 9.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Dava",
    nome: "Teresa",
    nota_portugues: 7.0,
    nota_historia: 6.5,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Francisco",
    nome: "Armando",
    nota_portugues: 9.5,
    nota_historia: 16.5,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Gove",
    nome: "Belinda",
    nota_portugues: 7.5,
    nota_historia: 13.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Guambe",
    nome: "Custódio",
    nota_portugues: 14.0,
    nota_historia: 10.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Langa",
    nome: "Deolinda",
    nota_portugues: 12.5,
    nota_historia: 6.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Lichucha",
    nome: "Emídio",
    nota_portugues: 6.0,
    nota_historia: 8.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Mabunda",
    nome: "Felismina",
    nota_portugues: 14.5,
    nota_historia: 11.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Machaieie",
    nome: "Guilherme",
    nota_portugues: 9.5,
    nota_historia: 13.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Machel",
    nome: "Hortência",
    nota_portugues: 11.5,
    nota_historia: 9.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Mahumana",
    nome: "Ivan",
    nota_portugues: 16.0,
    nota_historia: 15.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Mandlate",
    nome: "Jacinta",
    nota_portugues: 8.5,
    nota_historia: 13.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Manjate",
    nome: "Kelvin",
    nota_portugues: 12.5,
    nota_historia: 17.5,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Massinga",
    nome: "Leonor",
    nota_portugues: 15.0,
    nota_historia: 9.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Matavele",
    nome: "Marcelino",
    nota_portugues: 18.5,
    nota_historia: 6.5,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Matsimbe",
    nome: "Nádia",
    nota_portugues: 11.0,
    nota_historia: 15.5,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Mavie",
    nome: "Osvaldo",
    nota_portugues: 7.0,
    nota_historia: 12.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Mazuze",
    nome: "Palmira",
    nota_portugues: 5.5,
    nota_historia: 14.5,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Mondlane",
    nome: "Quitéria",
    nota_portugues: 15.5,
    nota_historia: 13.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Muchanga",
    nome: "Rogério",
    nota_portugues: 17.5,
    nota_historia: 9.5,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Muianga",
    nome: "Sérgio",
    nota_portugues: 14.5,
    nota_historia: 13.5,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Nacir",
    nome: "Tânia",
    nota_portugues: 13.0,
    nota_historia: 11.5,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Nhaca",
    nome: "Ussene",
    nota_portugues: 17.0,
    nota_historia: 18.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Nhamona",
    nome: "Vitória",
    nota_portugues: 11.5,
    nota_historia: 14.5,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Nhantumbo",
    nome: "Wilson",
    nota_portugues: 6.0,
    nota_historia: 15.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Nhassengo",
    nome: "Xavier",
    nota_portugues: 14.0,
    nota_historia: 19.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Ngovene",
    nome: "Yolanda",
    nota_portugues: 16.5,
    nota_historia: 9.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Novela",
    nome: "Zacarias",
    nota_portugues: 10.5,
    nota_historia: 14.5,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Sambo",
    nome: "Adélia",
    nota_portugues: 5.5,
    nota_historia: 11.5,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Simango",
    nome: "Bento",
    nota_portugues: 7.5,
    nota_historia: 6.5,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Sitoe",
    nome: "Cremilda",
    nota_portugues: 6.0,
    nota_historia: 16.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Sumbana",
    nome: "Domingos",
    nota_portugues: 7.0,
    nota_historia: 8.5,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Tembe",
    nome: "Edna",
    nota_portugues: 10.5,
    nota_historia: 17.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Timana",
    nome: "Faruk",
    nota_portugues: 6.0,
    nota_historia: 11.5,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Tivane",
    nome: "Graciete",
    nota_portugues: 12.5,
    nota_historia: 17.5,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Tovela",
    nome: "Hélio",
    nota_portugues: 16.5,
    nota_historia: 17.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Ubisse",
    nome: "Isaura",
    nota_portugues: 9.0,
    nota_historia: 11.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Wate",
    nome: "Júlio",
    nota_portugues: 10.0,
    nota_historia: 17.5,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Zandamela",
    nome: "Lídia",
    nota_portugues: 18.5,
    nota_historia: 7.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Zavala",
    nome: "Ana Maria",
    nota_portugues: 7.5,
    nota_historia: 8.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Amade",
    nome: "Carlos Eduardo",
    nota_portugues: 8.5,
    nota_historia: 12.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Bata",
    nome: "Esperança",
    nota_portugues: 13.0,
    nota_historia: 8.5,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Chambal",
    nome: "João Pedro",
    nota_portugues: 5.0,
    nota_historia: 11.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Dimande",
    nome: "Lurdes",
    nota_portugues: 10.0,
    nota_historia: 13.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Estevao",
    nome: "Pedro António",
    nota_portugues: 18.5,
    nota_historia: 14.5,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Faife",
    nome: "Fátima",
    nota_portugues: 12.0,
    nota_historia: 13.5,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Guilundo",
    nome: "Miguel",
    nota_portugues: 14.5,
    nota_historia: 6.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Hunguana",
    nome: "Helena",
    nota_portugues: 17.5,
    nota_historia: 16.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Inguane",
    nome: "Daniel",
    nota_portugues: 17.0,
    nota_historia: 16.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Jamal",
    nome: "Inês",
    nota_portugues: 10.5,
    nota_historia: 10.5,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Kambeu",
    nome: "Rui",
    nota_portugues: 6.5,
    nota_historia: 14.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Luis",
    nome: "Teresa",
    nota_portugues: 6.0,
    nota_historia: 6.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Macuacua",
    nome: "Armando",
    nota_portugues: 8.0,
    nota_historia: 7.5,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Nhabinde",
    nome: "Belinda",
    nota_portugues: 10.0,
    nota_historia: 5.5,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Ossumane",
    nome: "Custódio",
    nota_portugues: 5.0,
    nota_historia: 7.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Paulo",
    nome: "Deolinda",
    nota_portugues: 6.5,
    nota_historia: 10.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Quisse",
    nome: "Emídio",
    nota_portugues: 5.5,
    nota_historia: 17.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Rafael",
    nome: "Felismina",
    nota_portugues: 13.5,
    nota_historia: 7.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Sitole",
    nome: "Guilherme",
    nota_portugues: 8.5,
    nota_historia: 10.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Tamele",
    nome: "Hortência",
    nota_portugues: 10.0,
    nota_historia: 6.5,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Uamusse",
    nome: "Ivan",
    nota_portugues: 17.0,
    nota_historia: 19.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Vilanculos",
    nome: "Jacinta",
    nota_portugues: 11.5,
    nota_historia: 12.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Wamusse",
    nome: "Kelvin",
    nota_portugues: 6.0,
    nota_historia: 6.5,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Ximenes",
    nome: "Leonor",
    nota_portugues: 10.0,
    nota_historia: 8.5,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Yassine",
    nome: "Marcelino",
    nota_portugues: 16.5,
    nota_historia: 7.5,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Zunguza",
    nome: "Nádia",
    nota_portugues: 5.5,
    nota_historia: 18.5,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Abudo",
    nome: "Osvaldo",
    nota_portugues: 12.5,
    nota_historia: 7.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Bene",
    nome: "Palmira",
    nota_portugues: 12.5,
    nota_historia: 5.5,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Coana",
    nome: "Quitéria",
    nota_portugues: 12.5,
    nota_historia: 18.5,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Duma",
    nome: "Rogério",
    nota_portugues: 17.0,
    nota_historia: 14.5,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Eugenio",
    nome: "Sérgio",
    nota_portugues: 8.5,
    nota_historia: 10.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Fumo",
    nome: "Tânia",
    nota_portugues: 7.5,
    nota_historia: 16.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Gundane",
    nome: "Ussene",
    nota_portugues: 12.5,
    nota_historia: 16.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Homba",
    nome: "Vitória",
    nota_portugues: 9.5,
    nota_historia: 8.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Iassine",
    nome: "Wilson",
    nota_portugues: 16.5,
    nota_historia: 19.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Jose",
    nome: "Xavier",
    nota_portugues: 17.0,
    nota_historia: 16.5,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Kalimo",
    nome: "Yolanda",
    nota_portugues: 16.5,
    nota_historia: 15.5,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Lopes",
    nome: "Zacarias",
    nota_portugues: 8.0,
    nota_historia: 12.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Mabjaia",
    nome: "Adélia",
    nota_portugues: 10.0,
    nota_historia: 5.5,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Nhachungue",
    nome: "Bento",
    nota_portugues: 5.5,
    nota_historia: 9.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Omar",
    nome: "Cremilda",
    nota_portugues: 8.5,
    nota_historia: 14.5,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Pelembe",
    nome: "Domingos",
    nota_portugues: 18.5,
    nota_historia: 11.5,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Quim",
    nome: "Edna",
    nota_portugues: 18.0,
    nota_historia: 19.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Rungo",
    nome: "Faruk",
    nota_portugues: 18.5,
    nota_historia: 10.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Salimo",
    nome: "Graciete",
    nota_portugues: 8.0,
    nota_historia: 8.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Undela",
    nome: "Hélio",
    nota_portugues: 8.0,
    nota_historia: 8.0,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Viola",
    nome: "Isaura",
    nota_portugues: 13.5,
    nota_historia: 17.5,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Wetela",
    nome: "Júlio",
    nota_portugues: 17.0,
    nota_historia: 11.5,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Diurno",
    apelido: "Zeca",
    nome: "Lídia",
    nota_portugues: 14.0,
    nota_historia: 16.0,
  },
];

const DEMO_JORNALISMO_POS: Omit<PautaRow, "id" | "publicado">[] = [
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Pós-laboral",
    apelido: "Alberto",
    nome: "Helena",
    nota_portugues: 15,
    nota_historia: 14,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Pós-laboral",
    apelido: "Cossa",
    nome: "Daniel",
    nota_portugues: 10,
    nota_historia: 11,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Pós-laboral",
    apelido: "Machel",
    nome: "Inês",
    nota_portugues: 7.5,
    nota_historia: 8,
  },
  {
    ano_lectivo: ANO_LECTIVO,
    nivel: "Licenciatura",
    curso: "Jornalismo",
    regime: "Pós-laboral",
    apelido: "Tembe",
    nome: "Rui",
    nota_portugues: 13,
    nota_historia: 12.5,
  },
];

function demoPauta(curso: string, nivel: Nivel, regime: Regime): LinhaPauta[] {
  if (curso !== "Jornalismo" || nivel !== "Licenciatura") return [];
  const source = regime === "Pós-laboral" ? DEMO_JORNALISMO_POS : DEMO_JORNALISMO_DIURNO;
  return source.map((row, i) =>
    mapLinha({
      ...row,
      id: `demo-${regime}-${i}`,
      publicado: true,
    })
  );
}

export async function loadPautaPublica(input: {
  curso: string;
  nivel: Nivel;
  regime: Regime;
  anoLectivo?: string;
}): Promise<PautaPublica> {
  const anoLectivo = input.anoLectivo ?? ANO_LECTIVO;
  const supabase = getSupabase();
  if (supabase) {
    const { data } = await supabase
      .from("pauta_admissao")
      .select(
        "id, ano_lectivo, nivel, curso, regime, apelido, nome, nota_portugues, nota_historia, publicado"
      )
      .eq("ano_lectivo", anoLectivo)
      .eq("nivel", input.nivel)
      .eq("curso", input.curso)
      .eq("regime", input.regime)
      .eq("publicado", true);
    if (data?.length) {
      return {
        anoLectivo,
        nivel: input.nivel,
        curso: input.curso,
        regime: input.regime,
        linhas: ordenarPauta(data.map(mapLinha)),
      };
    }
  }
  return {
    anoLectivo,
    nivel: input.nivel,
    curso: input.curso,
    regime: input.regime,
    linhas: ordenarPauta(demoPauta(input.curso, input.nivel, input.regime)),
  };
}
